##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: 
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-csv

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Lost Bearings Skate Park Digital Exhibit
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Showcasing the Legacy of the Lost Bearings Skate Park and Skate Team
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: The Lost Bearings Skate Park, founded in 1992, continues to be a safe space for skates of all ages by providing a recreational space, a skate school, and a music venue to the Hemlock-Rook community. This exhibit highlights the activities and legacy of the Lost Bearings Skate Team and Park by sharing the materials in the collection.
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: skateboarding; history; skate park, skateboard
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Ana Bellamy

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: demo-compoundobjects-metadata 
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# ORGANIZATION SETTINGS
#
# Enter name and link for your organization (replacing the name and links below)
# These values will be used in attribution and data 
organization-name: "Hemlock-Rook Community Archive Center (HRCAC)"
organization-link: 
# Add logo image links if you would like them to appear in banner and footer. Delete or leave blank to remove logos.
organization-logo-banner: https://www.lib.uidaho.edu/collectionbuilder/cdil-black.png
organization-logo-nav: https://www.lib.uidaho.edu/collectionbuilder/cdil-white.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# Library directory location. This allows you to customize where the standard assets are found.
# provide a relative path in this repository or full url 
lib-assets: /assets/lib
# ignore stuff
exclude: [docs/, Rakefile, rakelib/, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
